using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using RideBound.Benchmarking.Claims;
using RideBound.Benchmarking.Contracts;

namespace RideBound.Benchmarking.Bundles;

public sealed class StrictBagItBundleBuilder
{
    private static readonly UTF8Encoding Utf8NoBom = new(false, true);
    private const string LogicalManifestPath = "data/bundle-manifest.json";
    private const string ClaimProfilePath = "data/provenance/claim-profile.json";
    private const string ClaimCheckPath = "data/claim-check.json";
    private const string VerificationReportPath = "data/verification-report.json";

    public async Task<StrictBagItBundleBuildResult> BuildAsync(
        StrictBagItBundleRequest request,
        CancellationToken cancellationToken = default)
    {
        ValidateRequest(request);
        var destination = Path.GetFullPath(request.DestinationDirectory);
        var parent = Path.GetDirectoryName(destination)
            ?? throw new ArgumentException("Bundle destination has no parent.", nameof(request));
        var staging = destination + ".building";
        var buildLockPath = destination + ".building.lock";

        if (Directory.Exists(destination) || File.Exists(destination))
        {
            throw new IOException("Existing bundle destinations are immutable.");
        }

        if (Directory.Exists(staging) || File.Exists(staging) || File.Exists(buildLockPath))
        {
            throw new IOException("An incomplete or concurrent bundle build already exists.");
        }

        Directory.CreateDirectory(parent);
        EnsureDirectoryNotReparse(parent);
        await using var buildLock = new FileStream(
            buildLockPath,
            FileMode.CreateNew,
            FileAccess.ReadWrite,
            FileShare.None,
            1,
            FileOptions.Asynchronous | FileOptions.DeleteOnClose);

        if (Directory.Exists(staging) || File.Exists(staging))
        {
            throw new IOException("Bundle staging path appeared during lock acquisition.");
        }

        Directory.CreateDirectory(staging);

        try
        {
            var pinned = request.PayloadSources
                .Select(source => PinSource(source, destination, staging))
                .OrderBy(source => source.Source.RelativePath, StringComparer.Ordinal)
                .ToArray();
            var planSource = pinned.Single(
                value => value.Source.RelativePath == "data/benchmark-plan.json");
            var canonicalPlan = await File.ReadAllBytesAsync(
                planSource.Source.SourcePath,
                cancellationToken);
            var decodedPlan = BenchmarkContractCodec.Decode<BenchmarkPlan>(canonicalPlan);

            if (!decodedPlan.IsSuccess || !canonicalPlan.AsSpan().SequenceEqual(decodedPlan.CanonicalBytes))
            {
                throw new InvalidDataException("Benchmark plan source is not exact canonical contract JSON.");
            }

            var planHash = BenchmarkIdentity.CalculateBenchmarkPlan(canonicalPlan);
            Directory.CreateDirectory(Path.Combine(staging, "data"));
            var artifacts = new List<BundleArtifact>();

            foreach (var source in pinned)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var target = ResolveInside(staging, source.Source.RelativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(target)!);
                await CopyPinnedAsync(source, target, cancellationToken);
                artifacts.Add(
                    new BundleArtifact(
                        source.Source.RelativePath,
                        source.LengthBytes,
                        source.Sha256,
                        source.Source.MediaType,
                        source.Source.Role,
                        source.Source.ProducerActivityId,
                        source.Source.SourceEntityIds));
            }

            var report = new BundlePackagingVerificationReport(
                "1.0.0",
                "ridebound-strict-bagit-verifier-v1",
                "wp6-bundle-verification-order-v1",
                "verified-before-atomic-publication",
                planHash,
                request.MetricSetHash);
            var reportBytes = BundleEvidenceJson.Encode(report);
            var reportFullPath = ResolveInside(staging, VerificationReportPath);

            if (File.Exists(reportFullPath))
            {
                throw new InvalidDataException(
                    "verification-report.json is generated by the builder and must not be supplied.");
            }

            Directory.CreateDirectory(Path.GetDirectoryName(reportFullPath)!);
            await WriteNewAsync(reportFullPath, reportBytes, cancellationToken);
            artifacts.Add(
                ArtifactForGenerated(
                    VerificationReportPath,
                    reportBytes,
                    "application/json",
                    BundleArtifactRole.VerificationReport,
                    "strict-bagit-builder-v1",
                    [request.BundleId]));
            var claimProfileBytes = ArtifactClaimProfileCatalog.GetV1CanonicalBytes();
            var claimProfileFullPath = ResolveInside(staging, ClaimProfilePath);

            if (File.Exists(claimProfileFullPath))
            {
                throw new InvalidDataException(
                    "claim-profile.json is generated by the builder and must not be supplied.");
            }

            Directory.CreateDirectory(Path.GetDirectoryName(claimProfileFullPath)!);
            await WriteNewAsync(claimProfileFullPath, claimProfileBytes, cancellationToken);
            artifacts.Add(
                ArtifactForGenerated(
                    ClaimProfilePath,
                    claimProfileBytes,
                    "application/json",
                    BundleArtifactRole.Provenance,
                    "wp6-claim-profile-catalog-v1",
                    [request.BundleId]));
            var readme = Utf8NoBom.GetBytes(
                "# RideBound WP6 mechanical evidence bundle\n\n" +
                "Evidence class: mechanical/development.\n" +
                "Same-team clean-process repeatability only.\n" +
                "This bundle is non-confirmatory mechanical evidence.\n" +
                "No effectiveness, non-inferiority, production SLA, ACM badge, independent reproducibility or replicability claim.\n" +
                "Resource measurements are local experiment controls only, not production latency, throughput or SLA evidence.\n" +
                "Public trip data does not contain observed commitment preference or satisfaction.\n");
            artifacts.Sort((left, right) => StringComparer.Ordinal.Compare(left.RelativePath, right.RelativePath));
            var claimSurfaceManifest = new LogicalBundleManifest(
                BenchmarkContractVersions.V1,
                request.BundleId,
                request.EvidenceClass,
                request.ClaimProfileId,
                planHash,
                request.MetricSetHash,
                request.SourceInventorySha256,
                request.RuntimeInventorySha256,
                artifacts);
            var machine = BundleEvidenceJson.DecodeExact<BundleMachineProvenance>(
                File.ReadAllBytes(ResolveInside(staging, "data/provenance/machine.json")));
            var sourceInventory = BundleEvidenceJson.DecodeExact<BundleSourceInventory>(
                File.ReadAllBytes(ResolveInside(staging, "data/source-inventory/repository.json")));
            var claimResult = ArtifactClaimChecker.Check(
                new ArtifactClaimCheckInput(
                    readme,
                    claimSurfaceManifest,
                    decodedPlan.Value!,
                    report,
                    machine,
                    sourceInventory));

            if (!claimResult.IsValid)
            {
                var witness = claimResult.Report.Witnesses[0];
                throw new BundleVerificationException(
                    BundleVerificationStage.Claims,
                    witness.Code,
                    witness.RelativePath,
                    $"Claim boundary failed at selector '{witness.Selector}' for rule '{witness.RuleId}'.");
            }

            var claimCheckBytes = BundleEvidenceJson.Encode(claimResult.Report);
            var claimCheckFullPath = ResolveInside(staging, ClaimCheckPath);

            if (File.Exists(claimCheckFullPath))
            {
                throw new InvalidDataException(
                    "claim-check.json is generated by the builder and must not be supplied.");
            }

            await WriteNewAsync(claimCheckFullPath, claimCheckBytes, cancellationToken);
            artifacts.Add(
                ArtifactForGenerated(
                    ClaimCheckPath,
                    claimCheckBytes,
                    "application/json",
                    BundleArtifactRole.ClaimCheck,
                    "wp6-artifact-claim-checker-v1",
                    [request.BundleId]));
            artifacts.Sort((left, right) => StringComparer.Ordinal.Compare(left.RelativePath, right.RelativePath));
            var logical = claimSurfaceManifest with { Artifacts = artifacts };
            var logicalBytes = BenchmarkContractCodec.Encode(logical);
            await WriteNewAsync(
                ResolveInside(staging, LogicalManifestPath),
                logicalBytes,
                cancellationToken);
            var bundleHash = BenchmarkIdentity.CalculateBundle(logicalBytes);
            var payloadFiles = EnumerateFiles(staging, "data");
            var payloadManifestBytes = CreateManifest(staging, payloadFiles);
            await WriteNewAsync(
                Path.Combine(staging, "manifest-sha256.txt"),
                payloadManifestBytes,
                cancellationToken);
            var payloadLength = payloadFiles.Sum(path => new FileInfo(path).Length);
            var bagIt = Utf8NoBom.GetBytes(
                "BagIt-Version: 1.0\nTag-File-Character-Encoding: UTF-8\n");
            var bagInfo = Utf8NoBom.GetBytes(
                "Bag-Software-Agent: RideBound strict-bagit-v1\n" +
                $"Bagging-Date: {request.BaggingDate}\n" +
                $"External-Identifier: {request.BundleId}\n" +
                $"Payload-Oxum: {payloadLength.ToString(CultureInfo.InvariantCulture)}.{payloadFiles.Length.ToString(CultureInfo.InvariantCulture)}\n");
            var verifierScript = Utf8NoBom.GetBytes(
                "param(\n" +
                "  [Parameter(Mandatory=$true)][string]$VerifierAssembly,\n" +
                "  [string]$ReportPath = (Join-Path (Split-Path -Parent $PSScriptRoot) ((Split-Path -Leaf $PSScriptRoot) + '.verification.json'))\n" +
                ")\n" +
                "$ErrorActionPreference = 'Stop'\n" +
                "dotnet $VerifierAssembly --bag $PSScriptRoot --report $ReportPath\n" +
                "exit $LASTEXITCODE\n");
            await WriteNewAsync(Path.Combine(staging, "bagit.txt"), bagIt, cancellationToken);
            await WriteNewAsync(Path.Combine(staging, "bag-info.txt"), bagInfo, cancellationToken);
            await WriteNewAsync(Path.Combine(staging, "README.md"), readme, cancellationToken);
            await WriteNewAsync(Path.Combine(staging, "verify.ps1"), verifierScript, cancellationToken);
            var tagFiles = new[]
            {
                Path.Combine(staging, "README.md"),
                Path.Combine(staging, "bag-info.txt"),
                Path.Combine(staging, "bagit.txt"),
                Path.Combine(staging, "manifest-sha256.txt"),
                Path.Combine(staging, "verify.ps1"),
            };
            await WriteNewAsync(
                Path.Combine(staging, "tagmanifest-sha256.txt"),
                CreateManifest(staging, tagFiles),
                cancellationToken);

            var verification = new StrictBagItBundleVerifier().Verify(staging);

            if (!verification.IsValid)
            {
                throw new BundleVerificationException(
                    verification.Issue!.Stage,
                    verification.Issue.Code,
                    verification.Issue.RelativePath,
                    verification.Issue.SafeMessage);
            }

            if (Directory.Exists(destination) || File.Exists(destination))
            {
                throw new IOException("Bundle destination appeared before atomic publication.");
            }

            Directory.Move(staging, destination);
            return new StrictBagItBundleBuildResult(
                destination,
                bundleHash,
                planHash,
                request.MetricSetHash,
                payloadFiles.LongLength,
                payloadLength);
        }
        catch
        {
            if (Directory.Exists(staging))
            {
                Directory.Delete(staging, recursive: true);
            }

            throw;
        }
    }

    private static void ValidateRequest(StrictBagItBundleRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        if (!Path.IsPathRooted(request.DestinationDirectory)
            || !StrictBundlePath.IsArtifactId(request.BundleId)
            || request.EvidenceClass is not (EvidenceClass.Mechanical or EvidenceClass.Development)
            || request.ClaimProfileId != "wp6-mechanical-only-v1"
            || !BundleSourceInventoryIdentity.IsSha(request.MetricSetHash)
            || !BundleSourceInventoryIdentity.IsSha(request.SourceInventorySha256)
            || !BundleSourceInventoryIdentity.IsSha(request.RuntimeInventorySha256)
            || !DateOnly.TryParseExact(
                request.BaggingDate,
                "yyyy-MM-dd",
                CultureInfo.InvariantCulture,
                DateTimeStyles.None,
                out _)
            || request.PayloadSources is null
            || request.PayloadSources.Count == 0)
        {
            throw new ArgumentException("Strict bundle request header is invalid.", nameof(request));
        }

        var ordered = request.PayloadSources
            .OrderBy(value => value.RelativePath, StringComparer.Ordinal)
            .ToArray();

        if (!request.PayloadSources.SequenceEqual(ordered)
            || ordered.Select(value => value.RelativePath)
                .Distinct(StringComparer.OrdinalIgnoreCase).Count() != ordered.Length
            || ordered.Any(value => !ValidateSourceMetadata(value)))
        {
            throw new ArgumentException(
                "Payload sources must be safe, sorted, and case-insensitively unique.",
                nameof(request));
        }

        var paths = ordered.Select(value => value.RelativePath).ToHashSet(StringComparer.Ordinal);
        var exactRequired = new[]
        {
            "data/benchmark-plan.json",
            "data/failures.ndjson",
            "data/exclusions.ndjson",
            "data/metrics/production.ndjson",
            "data/metrics/oracle.ndjson",
            "data/provenance/reproducibility.json",
            "data/provenance/runtime-inventory.json",
            "data/provenance/machine.json",
            "data/provenance/metric-registry.json",
            "data/provenance/run-store-plan.json",
            "data/source-inventory/repository.json",
        };

        if (exactRequired.Any(path => !paths.Contains(path))
            || paths.Contains(LogicalManifestPath)
            || paths.Contains(ClaimProfilePath)
            || paths.Contains(ClaimCheckPath)
            || paths.Contains(VerificationReportPath)
            || !paths.Any(path => path.StartsWith("data/datasets/", StringComparison.Ordinal))
            || !paths.Any(path => path.StartsWith("data/scenarios/", StringComparison.Ordinal))
            || !paths.Any(path => path.StartsWith("data/runs/", StringComparison.Ordinal)))
        {
            throw new ArgumentException("Payload source inventory is incomplete or reserved.", nameof(request));
        }
    }

    private static bool ValidateSourceMetadata(BundlePayloadSource source) =>
        source is not null
        && Path.IsPathRooted(source.SourcePath)
        && StrictBundlePath.IsSafeRelativePath(source.RelativePath, requireDataPrefix: true)
        && !string.IsNullOrWhiteSpace(source.MediaType)
        && source.MediaType.All(character => !char.IsControl(character))
        && StrictBundlePath.IsArtifactId(source.ProducerActivityId)
        && source.SourceEntityIds is not null
        && source.SourceEntityIds.Count > 0
        && source.SourceEntityIds.SequenceEqual(
            source.SourceEntityIds.Order(StringComparer.Ordinal))
        && source.SourceEntityIds.Distinct(StringComparer.Ordinal).Count()
            == source.SourceEntityIds.Count
        && source.SourceEntityIds.All(StrictBundlePath.IsArtifactId);

    private static PinnedPayloadSource PinSource(
        BundlePayloadSource source,
        string destination,
        string staging)
    {
        var fullPath = Path.GetFullPath(source.SourcePath);
        var info = new FileInfo(fullPath);

        if (!info.Exists
            || (info.Attributes & FileAttributes.ReparsePoint) != 0
            || IsInside(destination, fullPath)
            || IsInside(staging, fullPath))
        {
            throw new IOException("Payload source is missing, unsafe, or inside the bundle target.");
        }

        using var stream = new FileStream(
            fullPath,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            81_920,
            FileOptions.SequentialScan);
        var length = stream.Length;
        var sha256 = Convert.ToHexStringLower(SHA256.HashData(stream));
        return new PinnedPayloadSource(source with { SourcePath = fullPath }, length, sha256);
    }

    private static async Task CopyPinnedAsync(
        PinnedPayloadSource source,
        string destination,
        CancellationToken cancellationToken)
    {
        await using var input = new FileStream(
            source.Source.SourcePath,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            81_920,
            FileOptions.Asynchronous | FileOptions.SequentialScan);

        if (input.Length != source.LengthBytes)
        {
            throw new IOException("Payload source changed before copy.");
        }

        await using var output = new FileStream(
            destination,
            FileMode.CreateNew,
            FileAccess.Write,
            FileShare.None,
            81_920,
            FileOptions.Asynchronous | FileOptions.WriteThrough);
        await input.CopyToAsync(output, cancellationToken);
        await output.FlushAsync(cancellationToken);
        output.Flush(flushToDisk: true);
        input.Position = 0;
        var sourceHash = Convert.ToHexStringLower(SHA256.HashData(input));

        if (input.Position != source.LengthBytes || sourceHash != source.Sha256)
        {
            throw new IOException("Payload source changed while copied.");
        }

        output.Close();
        var targetInfo = new FileInfo(destination);
        var targetHash = Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(destination)));

        if (targetInfo.Length != source.LengthBytes || targetHash != source.Sha256)
        {
            throw new IOException("Payload copy identity differs from its pinned source.");
        }
    }

    private static BundleArtifact ArtifactForGenerated(
        string path,
        byte[] bytes,
        string mediaType,
        BundleArtifactRole role,
        string producer,
        IReadOnlyList<string> sources) =>
        new(
            path,
            bytes.LongLength,
            Convert.ToHexStringLower(SHA256.HashData(bytes)),
            mediaType,
            role,
            producer,
            sources);

    private static string[] EnumerateFiles(string root, string relativeRoot) =>
        Directory.GetFiles(
                ResolveInside(root, relativeRoot),
                "*",
                SearchOption.AllDirectories)
            .OrderBy(path => Relative(root, path), StringComparer.Ordinal)
            .ToArray();

    private static byte[] CreateManifest(string root, IEnumerable<string> files)
    {
        var builder = new StringBuilder();

        foreach (var path in files.OrderBy(path => Relative(root, path), StringComparer.Ordinal))
        {
            var relative = Relative(root, path);
            var hash = Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(path)));
            builder.Append(hash).Append("  ").Append(relative).Append('\n');
        }

        return Utf8NoBom.GetBytes(builder.ToString());
    }

    private static async Task WriteNewAsync(
        string path,
        byte[] bytes,
        CancellationToken cancellationToken)
    {
        await using var stream = new FileStream(
            path,
            FileMode.CreateNew,
            FileAccess.Write,
            FileShare.None,
            16_384,
            FileOptions.Asynchronous | FileOptions.WriteThrough);
        await stream.WriteAsync(bytes, cancellationToken);
        await stream.FlushAsync(cancellationToken);
        stream.Flush(flushToDisk: true);
    }

    private static string ResolveInside(string root, string relative)
    {
        var fullRoot = Path.GetFullPath(root) + Path.DirectorySeparatorChar;
        var full = Path.GetFullPath(
            Path.Combine(root, relative.Replace('/', Path.DirectorySeparatorChar)));

        if (!full.StartsWith(fullRoot, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("Bundle path escapes the target root.");
        }

        return full;
    }

    private static string Relative(string root, string path) =>
        Path.GetRelativePath(root, path).Replace('\\', '/');

    private static bool IsInside(string root, string path)
    {
        var relative = Path.GetRelativePath(Path.GetFullPath(root), Path.GetFullPath(path));
        return relative != ".."
            && !relative.StartsWith(".." + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && !Path.IsPathRooted(relative);
    }

    private static void EnsureDirectoryNotReparse(string path)
    {
        var info = new DirectoryInfo(path);

        if (!info.Exists || (info.Attributes & FileAttributes.ReparsePoint) != 0)
        {
            throw new IOException("Bundle parent directory is missing or a reparse point.");
        }
    }

    private sealed record PinnedPayloadSource(
        BundlePayloadSource Source,
        long LengthBytes,
        string Sha256);
}
