<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RideBound.Application\RideBound.Application.csproj" />
    <ProjectReference Include="..\RideBound.Contracts\RideBound.Contracts.csproj" />
    <ProjectReference Include="..\RideBound.Domain\RideBound.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
